### ISSUE TITLE
Добавить «Как быстро создать приложение»

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/new#106]
Добавить MD-файл в [content/articles](https://github.com/web-standards-ru/new/tree/master/content/articles)

- [Как быстро создать приложение](https://medium.com/p/5b9f008966cd)
- [mediumexporter](https://github.com/xdamman/mediumexporter)

В начале файла добавить мету:

```
---
title: "TITLE"
date: "YYYY-MM-DD"
---
```

Картинки сохранить и положить рядом в `images/`.

**Comment by petrovsa** [comment]
Если я правильно понимаю, то нужно оформить 2 статьи так же как и другие. Если я правильно понял, то берусь

**Comment by pepelsbey** [comment]
Не две, одну.

[См. пример пулреквеста](https://github.com/web-standards-ru/new/pull/105), который добавляет статью.

**Comment by pepelsbey** [comment]
Пометил «в работе», берите :) Спасибо!
