### ISSUE TITLE
Добавить «Новые логические свойства в CSS!»

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/new#108]
Добавить MD-файл в [content/articles](https://github.com/web-standards-ru/new/tree/master/content/articles)

- Статья: [Новые логические свойства в CSS!](https://medium.com/p/c5046c563640)
- Инструмент: [mediumexporter](https://github.com/xdamman/mediumexporter)

В начале файла добавить мету:

```
---
title: "TITLE"
date: "YYYY-MM-DD"
---

[ARTICLE]
```

- Папку назвать как псевдоним статьи: `logical-css-props`.
- Картинки сохранить и положить рядом в `images/`.
- Встраиваемые демки и видео положить как `<iframe>`

Внимание! Скажите, что начали работу над задачей прежде, чем приступите.

**Comment by pepelsbey** [comment]
Неправильный комментарий ;) Нужно «сейчас возьму»

**Comment by A-Ostrovnyy** [comment]
Нужно закрыть данное ишью.
