### ISSUE TITLE
Проблема с редактированием по правилам проекта

### ISSUE THREAD

**Issue by JediKnightIT** [web-standards-ru/new#110]
Перед началом работы ознакомился с https://github.com/JediKnightIT/new/blob/master/CONTRIBUTING.md

Все необходимые инструменты (**EditorConfig**, **Prettier**, **ESLint**) установлены.

![image](https://user-images.githubusercontent.com/105274/52380923-ab527880-2a80-11e9-8949-832839ddc7cc.png)

![image](https://user-images.githubusercontent.com/105274/52380929-af7e9600-2a80-11e9-8d0d-b131fe596b90.png)

1. Форкнул репозиторий;
2. Склонировал свой форк локально;
3. Установил зависимости.

По окончании установки зависимостей **git status** показал, что в рабочем каталоге были модифицированы 2 файла (**package.json** и **package-lock.json**)

![image](https://user-images.githubusercontent.com/105274/52380939-b73e3a80-2a80-11e9-95b9-f759b8cd3a1f.png)

Посмотрел изменения файлов в рабочем каталоге.
**git diff package-lock.json** показал следующее

![image](https://user-images.githubusercontent.com/105274/52380946-bd341b80-2a80-11e9-8d02-05977e949f0e.png)

**git diff package.json** показал следующее

![image](https://user-images.githubusercontent.com/105274/52380951-c2916600-2a80-11e9-9c64-a785d3edb829.png)

У данных файлов окончания строк стали LF.
Посмотрел остальные файлы в рабочем каталоге и у них окончания строк оказались CRLF 

![image](https://user-images.githubusercontent.com/105274/52380958-c91fdd80-2a80-11e9-8880-b9d2a18c9057.png)

В файле [.editorconfig](.editorconfig) прописана конфигурация окончания строк `end_of_line = lf`
Но EditorConfig не подцепился и не настроил редактирование по правилам проекта.

Хочу и в дальнейшем помогать, но для этого нужно решить данную проблему. Чтобы редактирование и работа проводилась по правилам проекта.

Работаю на операционной системе Windows 10. Среда разработки VSCode.

P.S. возможно я что-то не правильно сделал, прошу не судить строго)

**Comment by pepelsbey** [comment]
Заинлайнил картинки: если скопировать картинку в буфер обмена, а потом вставить — картинка загрузится.

**Comment by JediKnightIT** [comment]
Понял, спасибо Вадим.

**Comment by JediKnightIT** [comment]
Возможно стоит создать файл .gitattributes и явно прописать в нём 
`eol=lf`
Тем самым отключив преобразование строк при чтении из репозитория.

Т.е. при таких настройках не только внутри git, но и в рабочей директории у всех разработчиков, включая тех у которых стоит windows, будут одинаковые переводы строк -> **LF**

**Comment by pepelsbey** [comment]
Сделаете пулреквест? Если вам этот конфиг помогает, то поможет и другим.

**Comment by JediKnightIT** [comment]
Попробовал реализовать это у себя.
К сожалению данный конфиг подействовал только на 3 файла.
Сам файл **.gitattributes**, **package.json** и **package-lock.json**.
Продолжу поиски решения.

**Comment by FFxSquall** [comment]
@JediKnightIT У меня в одном из проектов `.gitattributs` с таким содержанием
```
*.vue   text eol=lf
*.js    text eol=lf
*.json  text eol=lf
*.md    text eol=lf
*.txt   text eol=lf
```
Все прекрасно работает на windows 10

**Comment by JediKnightIT** [comment]
@FFxSquall 
Прописал в **.gitattributs** следующий конфиг
![image](https://user-images.githubusercontent.com/24496044/53042329-16477a80-3497-11e9-92c7-695737626b6e.png)

Начал просматривать файлы. Как и писал выше подействовало только на 3 файла
![image](https://user-images.githubusercontent.com/24496044/53043485-9a026680-3499-11e9-89de-00796e8d4854.png)

![image](https://user-images.githubusercontent.com/24496044/53043491-9ff84780-3499-11e9-97c3-10ce3cafaea2.png)

![image](https://user-images.githubusercontent.com/24496044/53043497-a4246500-3499-11e9-87c8-a8ae43cfd4cc.png)

 У остальных файлов окончание строк осталось **CRLF**
![image](https://user-images.githubusercontent.com/24496044/53043668-0715fc00-349a-11e9-9468-8fc075edafbe.png)
![image](https://user-images.githubusercontent.com/24496044/53043684-0e3d0a00-349a-11e9-83b7-0676b0c13f9e.png)

При этом у файлов с расширением **.js** выводит следующее
![image](https://user-images.githubusercontent.com/24496044/53043838-77bd1880-349a-11e9-83b5-8793a82bba88.png)
![image](https://user-images.githubusercontent.com/24496044/53043853-7ee42680-349a-11e9-8f2b-32ee59cb9233.png)

По идее переводы строк у всех файлов должны были преобразоваться в **LF**, но к сожалению этого не произошло.

Возможно я что-то не так делаю?

**Comment by FFxSquall** [comment]
@JediKnightIT Ты не правильно понимаешь принцип действия `.gitattributs`. Он срабатывает при клонировании репозитория, если его нет берется настройка из git (`core.eol` по умолчанию `native`). Для windows native = CRLF. Можно глобально в git на windows задать, что бы окончания строк было в LF. Но так как многие этого не делают, в репозиторий сразу кладут  `.gitattributs` с настройками

**Comment by JediKnightIT** [comment]
@FFxSquall , да я не до конца понимаю принцип действия `.gitattributs`.
Но параметр конфигурации core.autocrlf у меня со значением true. 
Т.е. нормализация включена
![image](https://user-images.githubusercontent.com/24496044/53047578-c6bb7b80-34a3-11e9-9352-3dd49f6b8732.png)

![image](https://user-images.githubusercontent.com/24496044/53047322-35e4a000-34a3-11e9-9be3-86bd36b62492.png)

Мне об этом наставник рассказал ещё на интенсиве HTML и CSS, уровень 1 + Кантор это подробно изложил в [скринкасте про Git](http://learn.javascript.ru/screencast/git#config-autocrlf-2 ).
Вот я и не понимаю из-за чего не происходит нормализации.
