### ISSUE TITLE
Добавить «Список дел»

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/new#113]
Добавить маркдаун-файл в [content/articles](https://github.com/web-standards-ru/new/tree/master/content/articles)

- Статья: [Инклюзивные компоненты: список дел](https://medium.com/p/40a324436b3e)
- Инструмент для импорта в Маркдаун: [mediumexporter](https://github.com/xdamman/mediumexporter)

В начале файла добавить мету:

```
---
title: "TITLE"
date: "YYYY-MM-DD"
---

[ARTICLE]
```

- Папку назвать как псевдоним статьи: `a-todo-list`.
- Картинки сохранить и положить рядом в `images/`.
- Встраиваемые демки и видео положить как `<iframe>`

Внимание! Скажите, что начали работу над задачей прежде, чем приступите.

**Comment by annaindistress** [comment]
Я возьму
