### ISSUE TITLE
Добавить «Доступность интерактивных элементов»

### ISSUE THREAD

**Issue by A-Ostrovnyy** [web-standards-ru/new#116]
Добавить маркдаун-файл в [content/articles](https://github.com/web-standards-ru/new/tree/master/content/articles)
* Статья: [Советы по доступности интерактивных элементов на мобильных устройствах](https://medium.com/web-standards/mobile-a11y-aac0330569ae)
* Инструмент для импорта в Маркдаун: [mediumexporter](https://github.com/xdamman/mediumexporter)

В начале файла добавить мету:

```
---
title: "TITLE"
date: "YYYY-MM-DD"
---

[ARTICLE]
```
* Папку назвать как псевдоним статьи: `mobile-a11y`.
* Картинки сохранить и положить рядом в `images/`.
* Встраиваемые демки и видео положить как `<iframe>`

Внимание! Скажите, что начали работу над задачей прежде, чем приступите.

**Comment by jediyozh** [comment]
Я сделаю😊

**Comment by jediyozh** [comment]
#117
