### ISSUE TITLE
Добавить «Всё, что нужно знать про ARIA Live Regions»

### ISSUE THREAD

**Issue by A-Ostrovnyy** [web-standards-ru/new#121]
Добавить маркдаун-файл в [content/articles](https://github.com/web-standards-ru/new/tree/master/content/articles)

Статья: [Всё, что нужно знать про ARIA Live Regions](https://medium.com/web-standards/aria-live-regions-713f6a7813d3)
Инструмент для импорта в Маркдаун: [mediumexporter](https://github.com/xdamman/mediumexporter)
В начале файла добавить мету:
```
---
title: "TITLE"
date: "YYYY-MM-DD"
---

[ARTICLE]
```
- Папку назвать как псевдоним статьи: `aria-live-regions`.
- Картинки сохранить и положить рядом в `images/`.
- Встраиваемые демки и видео положить как `<iframe>`.

Внимание! Скажите, что начали работу над задачей прежде, чем приступите.

**Comment by EvgeniUPS** [comment]
Принял в работу

**Comment by pepelsbey** [comment]
Спасибо :)

**Comment by pepelsbey** [comment]
Добавлена в #122
