### ISSUE TITLE
Бекенд на фрейморке yii2

### ISSUE THREAD

**Issue by floor12** [web-standards-ru/new#123]
Я являюсь поклонником подкаста "веб стандарты", он многое к чему меня подтолкнул. Читая issues этого проекта у меня возник ряд вопросов. Я бы хотел в какой-то степени помочь проекту. Я занимаюсь веб разработкой более 15 лет, за последние 5 лет написал десятки проектов на фреймворке yii2 (хотя приходилось работать и с ларавель и симфони, но yii2 стал мои фаворитом). 
Насколько я понимаю, задачи перед проектом в целом стоят достаточно серьезные (агрегация эвентов (митапов, конференций) с возможностью добавления сторонними пользователями, размещение статей (как я понял формат на данном этапе выбран в виде markdown что я полностью одобряю) + в любой момент могут появляться какие-то другие требования и желания по функционалу сайта с достаточно амбициозными задачами (нести в массы идеи написания нормального лаконичного и доступного фронта). Я бы мог принять участи в рамках написания бекенда (и не только) на yii2 для этого проекта  (с блек джеком, барышнями и тестами), однако не знаю, насколько это актуально (ведь среди фронтендщиков много js поклонников).  
Хотелось бы это обсудить, потому что проект, судя по логу коммитов, немного застрял. А я как-то стал неравнодушен стал к веб-стандартам, так как после знакомства с ними страницы моих сайтов стали весить 200-400 килобайт вместо 3-10 мегабайт (это реально так). Спасибо.

**Comment by pepelsbey** [comment]
Евгений, спасибо за предложение!

У нас уже был опыт работы с админкой на WordPress. Опыт печальный. Сейчас задача сделать всё максимально открыто и на JS, чтобы всё было настолько просто и доступно любому. Тогда любой фронтендер сможет развивать сайт, редактировать и предлагать правки в виде пулреквестов. А файлы будут лежать у любого желающего в папке проекта на компьютере, редактировать в любимом текстовом редакторе и один коммит будет сразу публиковать всё на живой сайт.

Так что для сайта нам бэкенд точно не нужен. Но если понадобится что-то другое (бывают и такие задачи), мы обязательно вспомним :)
