### ISSUE TITLE
Сделать автосборку на gh-pages по merge в master

### ISSUE THREAD

**Issue by alexbaumgertner** [web-standards-ru/new#13]
PR https://github.com/web-standards-ru/new/pull/15

Использовать можно travis-ci, не забыть убрать пока сайт из индексирования (`robots.txt`).

`robots.txt`:
```
User-agent: *
Disallow: /
```

## Документация и ПО
- https://ru.wikipedia.org/wiki/Стандарт_исключений_для_роботов
- https://www.gatsbyjs.org/docs/deploy-gatsby/#github-pages
- https://docs.travis-ci.com/user/deployment/pages
- https://docs.travis-ci.com/user/pull-requests/
- https://docs.travis-ci.com/user/customizing-the-build/
- https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
- https://yarnpkg.com/en/package/gh-pages
- https://yarnpkg.com/en/package/gh-pages-travis

**Comment by alexbaumgertner** [comment]
@pepelsbey подключи пожалуйста travis-ci в https://travis-ci.org/profile/web-standards-ru

(документация https://docs.travis-ci.com/user/getting-started/#to-get-started-with-travis-ci, там по идее надо один чекбокс отметить)

**Comment by pepelsbey** [comment]
@alexbaumgertner done

**Comment by alexbaumgertner** [comment]
Попробовал задеплоить на https://web-standards-ru.github.io/new — 404.
@pepelsbey посмотри пожалуйста, для репозитория настроены gh-pages?

**Comment by alexbaumgertner** [comment]
Ветка и собраный код есть — https://github.com/web-standards-ru/new/tree/gh-pages

**Comment by pepelsbey** [comment]
<img width="409" alt="image" src="https://user-images.githubusercontent.com/105274/46529271-400c5600-c896-11e8-8a9f-21712f8bd9f3.png">

Ветка gh-pages уже активна для, должно работать.

**Comment by pepelsbey** [comment]
Заработало

**Comment by pepelsbey** [comment]
Страницы статей, правда, не работают https://web-standards-ru.github.io/articles/promises-explained/

**Comment by alexbaumgertner** [comment]
@pepelsbey смотрю-чиню.

**Comment by alexbaumgertner** [comment]
@pepelsbey как вариант, можно переименовать репозиторий в `web-standards-ru.github.io` 🙄

**Comment by pepelsbey** [comment]
Давай, прежде всего, сделаем и задеплоим `robots.txt` :)

```
User-agent: *
Disallow: /
```

**Comment by pepelsbey** [comment]
Я могу просто сделать кастомный домен для `gh-pages` и будет у нас new.web-standards.ru

**Comment by pepelsbey** [comment]
В общем, деплой работает. Давайте туда `robots.txt` заведём, а я в отдельной таске заведу кастомный домен, чтобы не нужно было фигнёй с путями заниматься.

**Comment by alexbaumgertner** [comment]
@pepelsbey я в GitHub и добавил: https://github.com/web-standards-ru/new/blob/feature/travis/public/robots.txt. 

Или ты говоришь, что нужно добавить не в `public/robots.txt`, а в корень проекта?

**Comment by pepelsbey** [comment]
@alexbaumgertner ай, сорри, я не в ту ветку смотрел — всё круто :)
