### ISSUE TITLE
 Календарь событий 

### ISSUE THREAD

**Issue by alexbaumgertner** [web-standards-ru/new#14]
Общее описание работы: https://github.com/web-standards-ru/new/issues/3

@pepelsbey @fogrew подскажите, как должен календарь работать?

**Comment by pepelsbey** [comment]
Выводить календарь на отдельной странице, см. репу [calendar-app](https://github.com/web-standards-ru/calendar-app), идеально с картой и фильтрами по городам. Но пока можно просто вывести что-то.

**Comment by fogrew** [comment]
@alexbaumgertner а эта ишья действительно нужна? Кажется, она полностью дублирует #3. Поэтому я закрою, чтобы не плодить одинаковых сущностей. Открой её заново, пожалуйста, если я чего-то недопонял.
