### ISSUE TITLE
Исправить отображение статей

### ISSUE THREAD

**Issue by alexbaumgertner** [web-standards-ru/new#17]
Как воспроизвести: пройти в статьи, в статью, нажать обратно — и ты на странице статей без списка:
![image 2018-10-11 09 48 35](https://user-images.githubusercontent.com/223620/46785577-d29b7200-cd3a-11e8-852b-2111aa60c77d.jpg)

Локально не воспроизводится.

**Comment by jt3k** [comment]
А есть уверенность что в продакшен-режиме проблема сохранится ?

**Comment by alexbaumgertner** [comment]
@jt3k похоже, что проблема только в продакшен-режиме. Похоже, прямой заход на `/articles` (http://new.web-standards.ru/articles/) не будет работать.
Что странно, так как страница https://github.com/web-standards-ru/new/blob/gh-pages/articles/index.html есть.

**Comment by fogrew** [comment]
@alexbaumgertner здесь всё сделано? Если баг исправлен, то закрой ишью, пожалуйста.

**Comment by alexbaumgertner** [comment]
Да, закрываю.
