### ISSUE TITLE
Запустить на генераторе статики новый сайт

### ISSUE THREAD

**Issue by fogrew** [web-standards-ru/new#2]
Для старта #1 нужно выбрать стек технологий, на котором будет крутиться сайт.
Дизайн надо по возможности стащить [со старого сайта](https://web-standards.ru/). Где-то наверняка придётся допилить.

Требования:
- все страницы редактируются в markdown (метаинформацию нужно уметь редактировать, например, в yaml в начале файла)
- полная генерация статики: никакого бэкэнда, пересборка для внесения изменений, изменения только с фронтенда
- кастомизируемый роутинг с вложенностями. все логичные старые адреса должны сохраниться, а с нелогичных потребуются редиректы.

**Comment by fogrew** [comment]
Предлагаю [gatsby](https://www.gatsbyjs.org/). Даёт из коробки всё, что нужно и многое помимо этого. Фротненд писать потребуется на реакте. Кажется, он уже плотно засел на месте самого популярного фреймворка на рынке и именно поэтому я за него.

**Comment by alexbaumgertner** [comment]
@fogrew Официальная документация одобряет gatsby!
https://reactjs.org/docs/create-a-new-react-app.html#gatsby

**Comment by pepelsbey** [comment]
Если он не будет сильно выкручивать руки в плане хранения контента и усложнять написание фронтенда — я не против.

**Comment by fogrew** [comment]
Он предлагает `.md` из коробки, так что не выкручивает!

@alexbaumgertner @nikolay-govorov @firefoxic может, кто-нибудь хочет начать проект?

**Comment by nikolay-govorov** [comment]
Сделаю заготовку в воскресенье

**Comment by alexbaumgertner** [comment]
@fogrew @nikolay-govorov 
Сделал заготовку https://github.com/web-standards-ru/new/pull/4, нужно ваше ревью.

**Comment by fogrew** [comment]
@alexbaumgertner Отлично! Спасибо! Давайте двигаться дальше.

Теперь нужно намутить базовый роутинг. Предлагаю пока всё ещё без дизайна сделать список текущих страниц. Условно: нужно сделать всё, чтобы отдать в вёрстку. Чтобы были какие-то общие шаблоны и на их месте можно было верстать новые.

@pepelsbey нам нужна новая карта сайта, чтобы мы могли превратить это в роутинг. Создал #5

**Comment by jt3k** [comment]
@fogrew, всем привет! 
А гетсби умеет в некое подобие реакт-компонентов внутри md-файлов, как это например делают на [веб-сайте preactjs](https://github.com/developit/preact-www/#custom-elements)

Мне понравилось в сайте preact что оно на лету подгружает md-файл и превращает его в html+реакт-компоненты внутри.

Правда оно напилено на коленке, и код там [вот такой](https://github.com/developit/preact-www/blob/master/src/components/content-region.js), зато в компоненты можно )

**Comment by pepelsbey** [comment]
Я вот тоже не понимаю. Кажется, что внутри контента будет только контент. А для всего остального использовать MD не слишком и нужно. Плюс у нас намечается вполне новаторская схема CSS-in-CSS, так что HTML с классами прямо в MD — вполне достаточно для любых целей.

**Comment by jt3k** [comment]
Спасиба за ваши отклики. Я тоже думаю что не стоит всё верстать на mdx ))

Компоненты в маркдаун-разметке могут быть  полезны например для листингов кода.
Например мы сможем переопределить компонент `<pre>` и в случае если внутри есть `<code class="lang-js">` разукрашивать/авто-форматировать код внутри., без избыточной вёрстки внутри наших md.файлов
Не могу придумать примеров больше )

Вцелом мне подход MDX не нравится т.к. они создают свой отдельный промежуточный формат,  мы вполне могли бы сделать предпарсер обычных MD-файлов который бы избирательно заменял специально подготовленный html-код на компоненты или просто вёрстку.

**Comment by langovoi** [comment]
Всем привет!
Расскажите чем помочь? У меня есть опыт и с Gatsby и с ICS.

**Comment by pepelsbey** [comment]
@langovoi постучи в Телеграме к [@pepelsbey](https://t.me/pepelsbey), я тебя в чат добавлю :) А по ICS и календарю — заходи в ишьи [web-standards-ru/calendar](https://github.com/web-standards-ru/calendar), там есть что делать. Спасибо :)

**Comment by pepelsbey** [comment]
Пока закрываю, раз процессы вылетели в окно.
