### ISSUE TITLE
Спроектировать дизайн

### ISSUE THREAD

**Issue by fogrew** [web-standards-ru/new#20]
Во избежание тысячи перевёрсываний сайта, хочется вначале заняться проектированием его дизайна.

**Цель сайта**: удобное получение контента
**Разделы**: [описаны в первой ишье](https://github.com/web-standards-ru/new/issues/1#user-content-sections)

Для начала нам нужны
- [ ] дизайн [статей](https://web-standards.ru/category/articles/)
- [ ] дизайн [календаря](https://frontendcalendar.tk/)

По ссылкам — их прежние версии.

Задача вакантная, ищем желающего заняться!

**Comment by fogrew** [comment]
@pepelsbey буду рад любым дополнениям. Особенно будет хорошо, если ты напишешь свои ожидания о том, как это может выглядеть.

Вброшу для старта обсуждений свои пожелания.

**Моё представление статей:**
- около 70 символов в ширину крупным шрифтом (16 или 18px)
- по шрифтам:
  - для текста: что-то уже в вебе привычное вроде Roboto, Open Sans или Source Sans
  - для заголовков: что-то тонкое аккуратное вроде Lora, Playfair Display, EB Garamond или Vollkorn, но размеры заголовков тогда стоит сильно увеличить от привычных
- картинки, которые «на всю ширину» — чуть шире контента на десктопе
- ссылки на другие статьи - по-прежнему списком, а не карточками под статьёй
- имя автора - хотелось бы после статьи с фотографией и описанием, но нам их неоткуда взять для старых статей, так что пока всё также едва заметно где-то одной строкой :( 

Также хорошо бы отрисовать 
- списки нумерованные и неупорядоченные с буллетами
- цитаты
- заголовки не всех уровней (1-3, мне кажется)

Чтобы дизайн не расходился от раздела к разделу, было бы круто делать сразу компонентную систему. Нам нужна цветовая палетка (стоит опираться на [руководство, связанное с лого WSD](https://github.com/web-standards-ru/logo)), оформление ссылок, кнопок, полей ввода и прочих контролов.

**Моё представление календаря:**
Думаю, что отсутствие сущности календаря в нынешнем календаре - это странно. И мне очень не хватает там его функционала. Особенно возможности посмотреть в разных видах: месяц - чтобы понять, общее число, неделя - чтобы понять свои возможности (на сколько митапов я осилю пойти).

Поэтому я бы сделал что-то вроде того, что предлагает [fullcalendar](https://fullcalendar.io/), только со сжатием по высоте недель без мероприятий и ивентами, занимающими расстояние больше своей клетки. 
А ещё добавил бы сверху фильтрации (страны и города) и смену вида

**Comment by fogrew** [comment]
Ещё на счёт общего каркаса несколько предложений:
- Предлагаю делать сайт, построенный блоками на всю ширину подобно лендингам (не браузера, а контентной области). Без сайдбаров.
- Меню - в шапке сайта. Только главные ссылки на основные разделы. Футер не должен прилипать при скролле (вряд ли читая статью, я резко захочу перейти в календарь).
- В футере - расширенное меню с подразделами: последние статьи для раздела статей, ближайшие события для календаря и т.п.

**Comment by pepelsbey** [comment]
> Думаю, что отсутствие сущности календаря в нынешнем календаре - это странно

Нынешний календарь — это всего лишь фантазия стороннего разработчика по мотивам данных. Никакого влияния на то, что мы можем с этим сделать он оказывать не должен.

**Comment by pepelsbey** [comment]
> Моё представление статей

Мне кажется, что ты сейчас начал «верстать» дизайн в голове. А его должны нарисовать, причём без вводных данных, вроде желательных шрифтов, ширины строки и прочего. Я бы хотел найти достаточно самостоятельного дизайнера для этой задачи.

Короче, проектирование это мне не очень понятно.

**Comment by alexbaumgertner** [comment]
@fogrew @pepelsbey кинем клич в соц сетях?

**Comment by pepelsbey** [comment]
Пока закрываю, раз процессы вылетели в окно.
