### ISSUE TITLE
Сверстать каркас сайта

### ISSUE THREAD

**Issue by fogrew** [web-standards-ru/new#21]
[Дизайна пока нет](https://github.com/web-standards-ru/new/issues/20), нужно сверстать хотя бы каркас страниц на HTML, без стилей.

А также надо сделать базовый каркас на страницах статей:
- [x] добавить шапку сайта в шаблон статьи
- [x] расставить ориентиры header, main, nav, footer
- [x] вставить [SVG-лого](https://github.com/web-standards-ru/logo) рядом с названием в шапке
- [x] сделать название ссылкой везде, кроме главной
- [ ] продумать уровни заголовков на всех страницах
- [x] добавить ссылки на соцсети в футере
- [x] сделать ссылку «отредактировать на Гитхабе» на странице каждой статьи

**Comment by fogrew** [comment]
@ariarzer возьмёшься? уже можно начинать.

**Comment by ariarzer** [comment]
Уже начинаю.

**Comment by pepelsbey** [comment]
Обновил описание задачи, вбросил новые пункты.

**Comment by ariarzer** [comment]
"сделать название ссылкой везде, кроме главной"
Какое название? Куда должна вести ссылка?
@fogrew ?

**Comment by pepelsbey** [comment]
@ariarzer задачу хоть и начинал Андрей, большая часть пунктов уже мои :)

> сделать название ссылкой везде, кроме главной

«Веб-стандарты» в шапке на главной текст, на остальных — ссылка на главную.

**Comment by pepelsbey** [comment]
Будем считать, что готово.
