### ISSUE TITLE
Придумать способ хранить общие ресурсы

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/new#28]
Сейчас у меня есть папка `public`, в которой среди мусора лежат `robots.txt` и `favicon.ico`. Редактор её вообще не видит, посольку вся папка исключена в игноре, с двумя исключениями. Кажется это очень кривой способ хранить ресурсы, общие для всего сайта, а ведь захочется её манифест положить, тач-иконки и всякое.

Это нам Гэтсби навязал или как-то так вышло? :) Давайте сделаем лучше. Например, отдельную папку `assets`, например. Я вообще немного удивлён, что у нас, например, `articles` лежит вне `src`.

**Comment by alexbaumgertner** [comment]
Сделал вариант https://github.com/web-standards-ru/new/pull/30

![web-standards-ru projects web-standards_new - data events 2018-12-01-minsk index md web-standards-ru 2018-12-09 12-34-52](https://user-images.githubusercontent.com/223620/49695639-1382fc00-fbaf-11e8-867a-ef539e40b951.png)
