### ISSUE TITLE
Научить сайт подгружать информацию из календаря событий

### ISSUE THREAD

**Issue by fogrew** [web-standards-ru/new#3]
Нужно понять, как подтягивать все изменения из пул реквестов [календаря](https://github.com/web-standards-ru/calendar) в сайт.

В идеале сайт должен быстро грузиться и кэшироваться с сервис-воркерами, поэтому подтягивать изменения календаря хотелось бы в сборке. И очень важно правильно их ревалидировать.

В крайнем случае можно сделать и на фронте, как [тут](https://frontendcalendar.tk/).

**Comment by fogrew** [comment]
Что мы хотим парсить?
* Можно парсить [общий файл](https://web-standards.ru/calendar.ics). Но тут без знатоков ICS формата не обойдётся. И мы всегда будем сталкиваться с BUS-фактором - всё время нужен будет особый человек, который это умеет. Изменения в этом механизме нельзя будет поручить остальным. 
* Можно парсить [папку events](https://github.com/web-standards-ru/calendar/tree/master/events) в гитхабе. Знаю, то ещё извращение, но зато как действовать - сразу абсолютно понятно.
* Можно парсить ту же папку [через API](https://developer.github.com/v3/repos/contents/#response-if-content-is-a-directory). Вроде звучит красивее. Но мне кажется, что сложнее))

**Comment by alexbaumgertner** [comment]
Нашел несколько парсеров ical
- https://www.npmjs.com/package/node-ical
- https://www.npmjs.com/package/ical.js

попробую применить.

**Comment by alexbaumgertner** [comment]
@fogrew @pepelsbey как сейчас работает добавление события в календарь?
Сначала добавляется файл в https://github.com/web-standards-ru/calendar/tree/master/events, потом обновляется 
https://web-standards.ru/calendar.ics?

**Comment by pepelsbey** [comment]
Да, после комита в master срабатывает хук, который собирает файл и деплоит его — всё на Тревисе. См. папку scripts, там сборка.

**Comment by fogrew** [comment]
Выполнено #22
