### ISSUE TITLE
Свести все тесты в npm t

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/new#31]
Сейчас prettier отдельно, линтер отдельно, а test тестирует только сборку Gatsby. Хотелось бы, чтобы `npm t` проверял общее состояние проекта по всем фронтам. Я сейчас немного запутался в количестве скриптов, которые там есть и не все понимаю — так бы сам сделал.

**Comment by alexbaumgertner** [comment]
Лучще `npm test` — проверяет все, а 
— `npm test:build`
— `npm lint`
и тд для всего остальное.

**Comment by pepelsbey** [comment]
Согласен :)
