### ISSUE TITLE
Не деплоится по коммиту

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/new#32]
На [new.web-standards.ru](https://new.web-standards.ru/) что-то совсем старое относительно мастера.

**Comment by h4** [comment]
У меня две новости, хорошая и не очень:

1. Починил отправку новых файлов
2. Продакшн-версии создаются с хешем в имени, то есть они каждый раз новые. Нужно что-то придумать с удалением старых версий с сервера, делать полную синхронизацию (с удалением всего, что нет на стороне сборки) я что-то опасаюсь.

**Comment by pepelsbey** [comment]
Опасаешься делат rm -rf?

**Comment by h4** [comment]
Да, ведь что-то может быть положено руками, файлы какие-нибудь секретные.
Если такого гарантированно не будет - можно и удаление сделать.

**Comment by pepelsbey** [comment]
Сейчас на поддомене ничего нет, кроме автодеплоя. Но вообще туда календарь и подкаст будут отдельно деплоиться. Видимо, нужно договориться, что деплой у нас один и только этот.

То есть сейчас — жги.

**Comment by h4** [comment]
Ну всё, теперь у нас только один источник истины – код в репозитории. Добавил удаление файлов при деплое.
