### ISSUE TITLE
Починить проверку на главную в событиях

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/new#33]
[Вот эта](https://github.com/web-standards-ru/new/blob/master/src/components/Header/Header.jsx#L8), в итоге на `/events/` с лого нет ссылки.

**Comment by KenanAivazov** [comment]
Уточнение: по идее, должен же быть `./` || `/events/`, т.к. у нас `/events/` - это ребёнок и при простом слеше будет идти открытие родителя ( т.е. просто `/` ). 

Или я что-то не правильно понимаю?)

**Comment by pepelsbey** [comment]
`/` должен вести на главную, с любой страницы, если вы об этом.

**Comment by pepelsbey** [comment]
@ariarzer посмотришь или перевесить на кого-нибудь ещё?

**Comment by pepelsbey** [comment]
Поправлено @redVi в #84
