### ISSUE TITLE
Проставить всем статьям мета-шапку в едином формате:

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/new#36]
```
---
title: "TITLE"
date: "YYYY.MM.DD"
---
```

1. Берётся одна из [articles](https://github.com/web-standards-ru/new/tree/master/content/articles)
2. Открывается `index.md`
3. Гуглится название статьи из `# Title` (находится либо [наш Medium](https://medium.com/web-standards), либо [старый сайт](https://web-standards.ru/))
4. Записывается дата и заголовок

Часто дата есть, но в другом формате. Часто дата стоит первой — это нужно исправить.

**Comment by FFxSquall** [comment]
Взял эту задачку

**Comment by pepelsbey** [comment]
Спасибо! Кажется это всё можно даже автоматизировать, инструкция примерная.

**Comment by FFxSquall** [comment]
@pepelsbey Такой вопрос. Стоит ли доверять датам которые уже написаны. Попробовал погуглить эти статьи, на медиум как правильно дата немного другая.  Пример "Невыполненные обещания веб-компонентов" - 17.03.2017 на медиум перевод от 18 апреля, а оригинал опубликован 13 марта

**Comment by pepelsbey** [comment]
Нужна дата публикации перевода, а не оригинальной статьи. Возможно, при экспорте с датами что-то пошло не так, так что доверять нельзя никому :О
