### ISSUE TITLE
Положить статику в сборку

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/new#38]
Я сейчас делаю `npm run build` и файлы `assets/*` (фавиконка и роботс) не попадают в корень. А вроде должны, нет?

**Comment by pepelsbey** [comment]
@alexbaumgertner можешь посмотреть, всё ли там хорошо?

**Comment by alexbaumgertner** [comment]
Сейчас посмотрю. Должны вроде в `/public`

**Comment by pepelsbey** [comment]
Мне главное, чтобы Гугл и браузры видели эти файлы, желательно без роутинга — то есть лучше их просто в корень.

**Comment by alexbaumgertner** [comment]
@pepelsbey скопирует в папку `/var/www/new.web-standards.ru/html`, это норм?

**Comment by pepelsbey** [comment]
То есть это вообще мимо Гэтсби? Кажется правильным.

**Comment by alexbaumgertner** [comment]
У нас Гетсби собирает все приложение в `/public`, эта папка является корневой для `web-standards.ru`, вот тут https://github.com/web-standards-ru/new/blob/master/.travis/deploy#L8 описано правило размещения файлов.

Так как я вынес негенерируемую статику (парадоксальное определение) в `assets`, я в https://github.com/web-standards-ru/new/pull/39 добавил ручное копирование этой статики в папку `/public`. Сделал в npm-скрипте, чтобы локально можно было тестировать. (https://github.com/web-standards-ru/new/blob/master/.travis/deploy работает только на проде).

Структура папки `/public`:
![public](https://user-images.githubusercontent.com/223620/50386981-7e7e1800-0703-11e9-95b5-e6e638b72df6.png)

**Comment by pepelsbey** [comment]
@alexbaumgertner закрывать?
