### ISSUE TITLE
Найти и исправить примеры тегов без бэктиков

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/new#45]
Например, [вот эта статья](https://github.com/web-standards-ru/new/blob/master/content/articles/front-end-interview-handbook/index.md). Иначе теги воспринимаются буквально и статью рвёт на части.

Есть
```
### Разница между <script>, <script async> и <script defer>
```
Надо
```
### Разница между `<script>`, `<script async>` и `<script defer>`
```

Кажется, можно написать какой-нибудь хитрый регекс и искать им.

Для начала, можно поискать и составить список проблемных статей, чтобы трекать прогресс.

**Comment by LeusMaximus** [comment]
Привет.
Сделал [pull-request](https://github.com/web-standards-ru/new/pull/51)

**Comment by LeusMaximus** [comment]
@pepelsbey Немного не понял вопрос.

**Comment by pepelsbey** [comment]
Перефразирую: как искали теги? :)

**Comment by LeusMaximus** [comment]
Я искал в редакторе с помощью регулярки. Но она не все находит.
```js
[^`]<[a-z]+
```
Вот такая была бы лучше (нужно будет еще раз просмотреть):
```js
([^`]<!?[a-zA-Z]+)|(^<!?[a-zA-Z]+)
```

**Comment by LeusMaximus** [comment]
Еще [один](https://github.com/web-standards-ru/new/pull/55) нашел

**Comment by martyns0n** [comment]
Задача более не актуальна?

**Comment by pepelsbey** [comment]
Нашёл последний спанчик, всё. Всем спасибо :)
