### ISSUE TITLE
Составить новую карту сайта

### ISSUE THREAD

**Issue by fogrew** [web-standards-ru/new#5]
Нужно прошерстить все страницы [старого сайта](https://web-standards.ru/) и понять, какие из ссылок являются артефактами вордпресса и ненужной частью реальных ссылок.

Например, кажется, что часть адреса /category/ не слишком нужна на новом движке.

Сейчас нужно составить соответствие: старая ссылка - новая ссылка. Предполагаю, что список старых ссылок будет [извлечён автоматически](https://www.npmjs.com/package/sitemap-generator-cli).

По сути соответствие можно сохранить в любом виде и месте, лишь бы оно было соответствием. Можно массивом объектов с двумя ключами `old` и `new`, можно гугл-табличкой, можно даже табличкой в `.md` файле. 

Также в рамках этой задачи нужно понять, какие разделы и страницы мы похороним при переезде.

**Comment by alexbaumgertner** [comment]
@fogrew у меня пустой файл генерируется, возможно бага в библиотеке 
https://github.com/lgraubner/sitemap-generator-cli/issues/28

**Comment by pepelsbey** [comment]
Предлагаю пока отталкиваться от контента. Сейчас у нас есть архив статей и сграбленные с Медиума новые переводы. Они будут жить так:

- `/articles/` — индекс статей
- `/articles/slug` — статья
- `/articles/slug/file` — ресурсы к статье, лежащие рядом с `index.md`

Другого актуального контента пока нет, но конечно будет:

- `/podcast/`
- `/podcast/`
- `/dictionary/`
- `/events/`

Их пока не трогаем и даже не проектируем. Сначала контент, потом остальное :)

**Comment by alexbaumgertner** [comment]
Новая карта сайта на текущий момент:
- `/articles/`— индекс статей
- `/articles/slug` — статья
- `/articles/slug/file` — ресурсы к статье, лежащие рядом с index.md

Позже добавить:
- `/podcast/`
- `/dictionary/`
- `/events/`

@fogrew можно закрывать задачу?
