### ISSUE TITLE
Добавить «Puppeteer для краулинга страниц»

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/new#56]
Добавить MD-файл в [content/articles](https://github.com/web-standards-ru/new/tree/master/content/articles)

- [Puppeteer для краулинга страниц](https://medium.com/p/7752dff36b68)
- [mediumexporter](https://github.com/xdamman/mediumexporter)

В начале файла добавить мету:
```
---
title: "TITLE"
date: "YYYY.MM.DD"
---
```

**Comment by TatianaFokina** [comment]
Возьмусь.
