### ISSUE TITLE
Удалить у всех статей заголовок

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/new#59]
Во всех статьях в [content/articles](https://github.com/web-standards-ru/new/tree/master/content/articles).

У нас и так заголовок и дата выводится из меты.

```jsx
return (
    <Layout>
        <h1>{frontmatter.title}</h1>
        <time>{frontmatter.date}</time>
        <div dangerouslySetInnerHTML={{ __html: html }} />
        <a href={`${github}/${path}/index.md`}>
            Отредактировать на Гитхабе
        </a>
    </Layout>
);
```

Так что если меты вдруг нет — перенести заголовок туда. Если есть — просто удалить.

**Comment by TatianaFokina** [comment]
Сделаю.
