### ISSUE TITLE
Описать в ридми как завести сайт локально

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/new#62]
Когда будет готов `CONTRIBUTING.md` в #68.

**Comment by ishpartko** [comment]
беру Windows

**Comment by inomdzhon** [comment]
А имеет ли смысл описывать это для каждой платформы?
Требования же простые: **git** и **node > 8**.

Для каждой системы по сути это оборачивается в идентичные команды:
1) `git clone https://github.com/web-standards-ru/new.git`
2) `cd new`
3) `npm ci`
4) `npm run develop`
5) перейти на http://localhost:8000/
А дальше уже нюансы самих PR.

**Comment by pepelsbey** [comment]
Ну да, я бы не стал расписывать отдельно. Просто я указал платформы, чтобы проверить и добавить какие-нибудь нюансы, если они будут.

**Comment by pepelsbey** [comment]
Можно, на самом деле, всё расписать в #68, а оттуда уже взять выжимку про запуск и тесты для ридми. А там ещё нужно про перезагрузку, тесты, линтер.

**Comment by pepelsbey** [comment]
Поменял суть задачи, давайте сначала с расширенным описанием в #68 разберёмся.
