### ISSUE TITLE
Вынести функцию для красивой даты

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/new#71]
Ведь [beautyDate](https://github.com/web-standards-ru/new/blob/master/src/templates/article.jsx#L23-L39) может пригодиться где-то ещё, кроме как для вывода статей. Но тут нужно понимать архитектуру Gatsby и как правильно всё провернуть.

@langovoi, возьмёшься?

**Comment by pepelsbey** [comment]
Возможно, стоит её отрефакторить по дороге, чтобы можно было и такое вывести красиво:

```
    Место: Санкт-Петербург, Россия
    Начало: 1/24/2019, 6:30:00 PM
    Конец: 1/24/2019, 10:00:00 PM
```

**Comment by ishpartko** [comment]
могу написать для нового формата даты, а вы перенесете в нужное место

**Comment by langovoi** [comment]
На самом деле нужно от него избавиться, а во всех статьях даты исправить на валидный (чтобы они были по ISO 8601, при получений из GraphQL), тогда можно везде использовать `new Date(dateString).toLocaleDateString`

**Comment by langovoi** [comment]
`toLocaleDateString` часть спеки `Intl`, для интернализации, которая использует CLDR под капотом.

**Comment by ishpartko** [comment]
> 
> 
> На самом деле нужно от него избавиться, а во всех статьях даты исправить на валидный (чтобы они были по ISO 8601, при получений из GraphQL), тогда можно везде использовать `new Date(dateString).toLocaleDateString`

Предлагаете к каждому вызову прибавлять date.toLocaleDateString('ru-RU', {
            day: 'numeric',
            month: 'long',
            year: 'numeric',
        });

?

**Comment by langovoi** [comment]
> Предлагаете к каждому вызову прибавлят

Только в местах, где нужно отформатировать дату.

**Comment by ishpartko** [comment]
> 
> 
> > Предлагаете к каждому вызову прибавлять
> 
> Только в местах, где нужно отформатировать дату.

Как я понял сейчас ее бьютить везде планируют, для этого эта функция - типа обёртки

**Comment by langovoi** [comment]
Эта функция делает объект `Date` из строки вида `YYYY.MM.DD`, а потом вызовает `toLocaleDateString`.

В каждом месте вывода могут быть свои правила форматирования (только дата, дата и время, дата с днём недели текстом и тп), за это отвевают параметры передаваемые в `toLocaleDateString`

**Comment by pepelsbey** [comment]
Передумали.
