### ISSUE TITLE
Вывести дату красиво в списке статей

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/new#74]
Сейчас там `01.01.3000`, а надо `1 января 3000`. Шаблон [articleList](https://github.com/web-standards-ru/new/blob/master/src/templates/articleList.jsx), вроде.

Но сначала лучше дождаться #75.

**Comment by FFxSquall** [comment]
@pepelsbey Случайно сюда линканул. Но для списка надо по аналогии сделать.

**Comment by FFxSquall** [comment]
@pepelsbey можно закрыть.
