### ISSUE TITLE
Перевести все даты статей в новый формат

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/new#75]
- [x] Перевести даты в новый формат
- [x] Вывести даты в новом формате

## Перевести

Сейчас это
```
date: "2018.02.19"
```
А нужно:
```
date: "2018-02-19"
```
Я полагаю, что простая регулярка по `content/articles/**/*.md` легко справится с задачей.

## Вывести

Сейчас в шаблоне [src/templates/article.jsx](https://github.com/web-standards-ru/new/blob/master/src/templates/article.jsx#L44) есть функция-хелпер и её использование. Функцию нужно выпилить, а использование заменить на `toLocaleDateString` [по мотивам дискуссии](https://github.com/web-standards-ru/new/pull/72#discussion_r249271906).

**Comment by ishpartko** [comment]
Кстати, а вы же там хотели что-то из Gatsby использовать вместо `toLocaleDateString`?

**Comment by FFxSquall** [comment]
@pepelsbey @ishpartko Могу в своем пуллреквесте поправить функцию как описано в комментариях. Как через Gatsby это сделать не знаю. Можно потом отдельной задачей выпелить функцию полностью если нужно. Делать?

**Comment by FFxSquall** [comment]
@pepelsbey не успел в тот же пуллреквест, сейчас новый сделаю тогда

**Comment by pepelsbey** [comment]
Я слишком быстро мёржу, извинити
