### ISSUE TITLE
Починить (дописать?) плагин вставки картинок

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/new#95]
[В недавнем коммите](https://github.com/web-standards-ru/new/commit/e6a02479c86b18cbf62d80a460b63c3c3d510d59) я упростил вставку картинок: теперь они вставляются просто так вместо навороченной системы с непонятным кодом. Вместо [gatsby-remark-images](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-images) стал использоваться плагин [gatsby-remark-static-images](https://github.com/Mrtenz/gatsby-remark-static-images), но он кажется не умеет брать картинки из HTML, только из маркдауна. Об этом я [завёл баг](https://github.com/Mrtenz/gatsby-remark-static-images/issues/1) в их репозитории, но особых надежд у меня нет.

Что этот плагин вообще делает: берёт относительный путь картинки и кидает её в сборку, а потом вставляет правильный прямой путь вместо относительного. Нужно добавить обработку HTML-тегов `<img>` в этот плагин по примеру прежнего.

**Comment by pepelsbey** [comment]
[Есть решение от автора плагина](https://github.com/Mrtenz/gatsby-remark-static-images/issues/1), но не дойдут руки проверить. Кто-нибудь может?

**Comment by FFxSquall** [comment]
@pepelsbey Вроде как не помогло. Я проверил, что пакет правильно слинковался. Потом выполнил build в сгенерированном html всё без изменений.
```
<figure>
    <img src="image/1.png" alt="Поисковые запросы по фреймворкам: январь 2014 — декабрь 2018">
</figure>
```

**Comment by pepelsbey** [comment]
Написал автору, ждём ответа. Ну или можно написать свой плагин или поискать альтернативы.

**Comment by LxPvlv** [comment]
А зачем в маркдауне использовать хтмл для картинок?
вот такой код ведь прекрасно работает `![ alt text](images/1.gif)`

**Comment by pepelsbey** [comment]
А если хочется класс на картинку поставить? А если хочется завернуть в `<figure>` и добавить подпись?

**Comment by LxPvlv** [comment]
Похоже этот плагин решает проблему 
https://www.gatsbyjs.org/packages/gatsby-remark-figure-caption/?=gatsby-remark-figure-caption

**Comment by LxPvlv** [comment]
Хотя, может и не решает. Похоже что он добавляет всем фигурам один гласс

**Comment by FFxSquall** [comment]
@LxPvlv странно, а у меня что-то не завилось, хотя в node_modules после link была слинкованая папка. Впрочем я мог что-то упустить

**Comment by pepelsbey** [comment]
Ну вот у меня тоже не завелось с линкованием. Может в способе проблема какая.

**Comment by pepelsbey** [comment]
Думаю попробовать установить пакет в зависимости прямо с Гитхаба, только соображу как именно это сделать, до сих пор не приходилось.

**Comment by FFxSquall** [comment]
@pepelsbey Можно в package.json указать ссылку на git.
```
"gatsby-remark-static-images": "git+ssh://git@github.com:Mrtenz/gatsby-remark-static-images.git#master",
```
Сейчас правда проверить, не могу.

**Comment by LxPvlv** [comment]
Установил с гитхаба `npm install https://github.com/Mrtenz/gatsby-remark-static-images.git`
решил не заморачиваться с линковкой, собрал прямо в node_modules
`cd node_modules/gatsby-remark-static-images`
`npm install`
`npm run build`

**Comment by LxPvlv** [comment]
> @LxPvlv в смысле, что его правки сработали и можно релизить?
я думаю, если установка из гита работает, автор делает новую версию npm пакета, и тогда уже можно релизить.
