### ISSUE TITLE
Добавить «Что нового в JavaScript 2019»

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/new#99]
Добавить MD-файл в [content/articles](https://github.com/web-standards-ru/new/tree/master/content/articles)

- [Что нового в JavaScript 2019](https://medium.com/p/417d8b406346)
- [mediumexporter](https://github.com/xdamman/mediumexporter)

В начале файла добавить мету:

```
---
title: "TITLE"
date: "YYYY-MM-DD"
---
```

Картинки сохранить и положить рядом в `images/`.

**Comment by A-Ostrovnyy** [comment]
Я берусь
